[package]
name = "ControlScrap"
version = "1.0.0"
edition = "2021"

[dependencies]
reqwest = {version="0.11.17", features = ["blocking"]}
url = "2.3.1"
urlencoding = "2.1.2"
rand = "0.8.5"
chrono = "0.4.38"
scraper = "0.21.0"
regex = "1.11.1"
dirs = "6.0.0"
